name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install dependencies 
        run: pip install -r requirements.txt

      - name: run tests
        run: pytest

      - name: login to docker hub 
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build Docker image
        run: docker build -t goyalvansh717/devops-demo-app:latest .
      
      - name: push docker image
        run: docker push goyalvansh717/devops-demo-app:latest
